# Monorepo Selective Build Workflow
# Intelligently builds only changed packages/services in a monorepo
# Uses path filtering and dependency detection for optimal CI performance

name: Monorepo Selective Build

# Trigger configuration
on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Detect which packages/services have changed
  detect-changes:
    name: Detect Changed Packages
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Output which packages changed
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      api: ${{ steps.filter.outputs.api }}
      shared: ${{ steps.filter.outputs.shared }}
      any-code: ${{ steps.filter.outputs.frontend == 'true' || steps.filter.outputs.backend == 'true' || steps.filter.outputs.api == 'true' }}

    steps:
      - uses: actions/checkout@v4

      # Use paths filter to detect changes
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'packages/frontend/**'
              - 'packages/shared/**'
            backend:
              - 'packages/backend/**'
              - 'packages/shared/**'
            api:
              - 'packages/api/**'
              - 'packages/shared/**'
            shared:
              - 'packages/shared/**'
            workflows:
              - '.github/workflows/**'

  # Job 2: Test and build shared package (always needed if shared changed)
  build-shared:
    name: Build Shared Package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: detect-changes
    # Only run if shared package changed
    if: needs.detect-changes.outputs.shared == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/shared/package-lock.json'

      - name: Install dependencies
        working-directory: packages/shared
        run: npm ci

      - name: Run tests
        working-directory: packages/shared
        run: npm test

      - name: Build shared package
        working-directory: packages/shared
        run: npm run build

      # Cache the build output for dependent jobs
      - name: Cache shared build
        uses: actions/cache/save@v4
        with:
          path: packages/shared/dist
          key: shared-build-${{ github.sha }}

  # Job 3: Build frontend (only if frontend changed)
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [detect-changes, build-shared]
    # Run if frontend changed, or skip shared build if it didn't change
    if: |
      always() &&
      needs.detect-changes.outputs.frontend == 'true' &&
      (needs.build-shared.result == 'success' || needs.build-shared.result == 'skipped')

    steps:
      - uses: actions/checkout@v4

      # Restore shared package if it was built
      - name: Restore shared build
        if: needs.detect-changes.outputs.shared == 'true'
        uses: actions/cache/restore@v4
        with:
          path: packages/shared/dist
          key: shared-build-${{ github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: packages/frontend
        run: npm ci

      - name: Run linting
        working-directory: packages/frontend
        run: npm run lint

      - name: Run tests
        working-directory: packages/frontend
        run: npm test

      - name: Build frontend
        working-directory: packages/frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: packages/frontend/dist/
          retention-days: 7

  # Job 4: Build backend (only if backend changed)
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [detect-changes, build-shared]
    if: |
      always() &&
      needs.detect-changes.outputs.backend == 'true' &&
      (needs.build-shared.result == 'success' || needs.build-shared.result == 'skipped')

    steps:
      - uses: actions/checkout@v4

      # Restore shared package if it was built
      - name: Restore shared build
        if: needs.detect-changes.outputs.shared == 'true'
        uses: actions/cache/restore@v4
        with:
          path: packages/shared/dist
          key: shared-build-${{ github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/backend/package-lock.json'

      - name: Install dependencies
        working-directory: packages/backend
        run: npm ci

      - name: Run linting
        working-directory: packages/backend
        run: npm run lint

      - name: Run unit tests
        working-directory: packages/backend
        run: npm run test:unit

      - name: Run integration tests
        working-directory: packages/backend
        run: npm run test:integration

      - name: Build backend
        working-directory: packages/backend
        run: npm run build

  # Job 5: Build API service (only if API changed)
  build-api:
    name: Build API Service
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [detect-changes, build-shared]
    if: |
      always() &&
      needs.detect-changes.outputs.api == 'true' &&
      (needs.build-shared.result == 'success' || needs.build-shared.result == 'skipped')

    # API uses Python, different from other Node.js packages
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'packages/api/requirements.txt'

      - name: Install dependencies
        working-directory: packages/api
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linting
        working-directory: packages/api
        run: ruff check .

      - name: Run tests
        working-directory: packages/api
        run: pytest

      - name: Build Docker image (if Dockerfile exists)
        if: hashFiles('packages/api/Dockerfile') != ''
        working-directory: packages/api
        run: docker build -t api:${{ github.sha }} .

  # Job 6: E2E tests (only if any code changed)
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [detect-changes, build-frontend, build-backend, build-api]
    # Run E2E only if builds succeeded and code changed
    if: |
      always() &&
      needs.detect-changes.outputs.any-code == 'true' &&
      (needs.build-frontend.result == 'success' || needs.build-frontend.result == 'skipped') &&
      (needs.build-backend.result == 'success' || needs.build-backend.result == 'skipped') &&
      (needs.build-api.result == 'success' || needs.build-api.result == 'skipped')

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install E2E dependencies
        working-directory: packages/e2e
        run: npm ci

      - name: Run E2E tests
        working-directory: packages/e2e
        run: npm run test:e2e

  # Job 7: Publish changed packages (only on main)
  publish-packages:
    name: Publish Changed Packages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [detect-changes, build-shared, build-frontend, build-backend]
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      needs.detect-changes.outputs.any-code == 'true'

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        package:
          - name: shared
            changed: ${{ needs.detect-changes.outputs.shared }}
          - name: frontend
            changed: ${{ needs.detect-changes.outputs.frontend }}
          - name: backend
            changed: ${{ needs.detect-changes.outputs.backend }}

    steps:
      - uses: actions/checkout@v4
        if: matrix.package.changed == 'true'

      - name: Setup Node.js
        if: matrix.package.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish ${{ matrix.package.name }}
        if: matrix.package.changed == 'true'
        working-directory: packages/${{ matrix.package.name }}
        run: |
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# Configuration notes:
#
# Monorepo structure example:
# packages/
#   ├── shared/           - Shared utilities/components
#   ├── frontend/         - Frontend application
#   ├── backend/          - Backend service
#   ├── api/              - API service (Python)
#   └── e2e/              - E2E tests
#
# Key features:
# 1. Path filtering detects which packages changed
# 2. Only builds affected packages (saves CI time/cost)
# 3. Dependency management (shared package built first)
# 4. Conditional job execution based on changes
# 5. Parallel builds for independent packages
#
# Required setup:
# - Each package has its own package.json / requirements.txt
# - Shared package is a dependency of other packages
# - E2E tests can run against all packages
#
# Customization tips:
# 1. Adjust paths in filters to match your monorepo structure
# 2. Add more packages as needed
# 3. Modify dependency chains based on your architecture
# 4. Add deployment jobs for specific packages
# 5. Use workspace tools (npm workspaces, pnpm, yarn workspaces)
